### ISSUE TITLE
Not working / missing solenoid turn off signal in M6051 communication

### ISSUE THREAD

**Issue by felixrinker** [teddych/railcontrol#3]
While playing around with RailControl and the old Märklin Central Unit 6021 + Interface 6051 in combination with k73 decoders, I noticed that the solenoids of the M-Track switches never turn off after a switching operation.

After some internet research I noticed that the Interface 6051 documentation describes, that an extra solenoid turn off signal (32) needs to be send approximately 150 (min. 80 - 1000) milliseconds after  a switching operation.

Is this command missing or is the malfunction related to another issue?

**Comment by teddych** [comment]
Basically the command to turn off should be sent.
This is done in method Hardware::HardwareInterface::AccessoryOnOrOffStatic()
Could you please try to extend the delay in configuration and try again?
And can you please send me a log? Prefered in the RailControl Forum

**Comment by teddych** [comment]
Thanks for reporting the problem. And also thanks for a solution (via RailControl-Forum)!
It is fixed now.
