### ISSUE TITLE
Feature Idea: Keyboard Shortcuts

### ISSUE THREAD

**Issue by AgentSmith0** [teddych/railcontrol#4]
What about adding (configurable) keyboard shortcuts for important functionalities like booster power, emergency stop and speed levels?

**Comment by haschler** [comment]
How would you imagine the "configurable" shortcuts? Via configuration file (easy) or via WebUI (harder)?

**Comment by teddych** [comment]
Could you please post your ideas in the RailControl forum? https://www.railcontrol.org/forum/

**Comment by haschler** [comment]
Hallo Teddy, leider bekomme ich beim Versuch, im Forum zu posten die Fehlermeldung: "Forbidden. *** Email does not exist.

**Comment by teddych** [comment]
Hallo,
Ja natürlich. Die Idee ist gut! Insbesondere die Space-Taste für Stop/Go wäre sehr praktisch! Ich hab mir aber noch keine weiteren Gedanken darüber gmacht.
Gruss Teddy

**Comment by ingoha** [comment]
Das geht grundsätzlich wirklich ganz einfach: Fügt zum Testen einfach vor dieser Zeile https://github.com/teddych/railcontrol/blob/91deee7f7a92dc5e9939e44b0b22e8b996c24ff8/html/javascript.js#L1770 folgenden Code ein:
`                body.addEventListener('keydown', function(event) {
                        if (event.key === " ")
                        {
                                var on = !document.getElementById('skip_booster').classList.contains('button_on');var url = '/?cmd=booster&on=' + (on ? '1' : '0') + '';fireRequestAndForget(url);return false;
                        }
                }, true);
`
Die spannendere Frage ist, wie man die Konfiguration bzw. das Speichern der benutzerdefinierten Tastenkombinationen umsetzt...

**Comment by ingoha** [comment]
Auch hier in meiner [branch](/ingoha/railcontrol/tree/hotkeys)

**Comment by teddych** [comment]
Kannst du einen Pullrequest stellen, dann kann ich das übernehmen 😊

Danke für die Umsetzung!

**Comment by ingoha** [comment]
Mach ich gleich; ist allerdings "quick and dirty" und nur die Leertaste für den Booster.
Damit man weitere Funktionen per Tastatur schalten (und evtl. auch frei zuordnen) kann, müßte man m.E. eine Liste dieser Funktionen erstellen und den JS-Code dahingehend ein wenig umbauen.
@AgentSmith0 vielleicht hast Du ja Lust, die Liste mit den Funktionen zu erstellen (=also was soll man alles per konfigurierbarer Tastenkombination schalten können?)

**Comment by teddych** [comment]
Hallo zusammen

Ich habe für die Lok ganz links noch Keyboard-Shortcuts eingefügt:
Pfeil links-rechts/4-6 ist Fahrtrichtung
Pfeil hoch-runter/8-2 ist schneller-langsamer
Seite hoch-runter/9-3 ist viel schneller-viel langsamer
Einfügen/Insert/0 ist anhalten

Space ist nach wie vor Strom aus/ein

Gruss
Teddy

**Comment by teddych** [comment]
Der Apetit kommt mit dem Essen :-)
Was ist dein Vorschlag für die drei Fahrstufen bzw. für die Lokauswahl?
